config/routes.rb
HgOpinions::Application.routes.draw do
  
  root :to => 'opinions#index'
  get 'ecommerce/:ecommerce_id/opinions', :to => 'opinions#index', :as => "client_opinions"

  get 'fake-api', :to => 'opinions#fake_api'
  get 'test', :to => 'opinions#test'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/opinions_controller.rb
require 'net/https'
require 'json'
require 'faraday'

class OpinionsController < ApplicationController

  before_filter :load_data

  def index

    if params[:ecommerce_id]
      @ecommerce_id = params[:ecommerce_id]
      @default_limit = OPINIONS_CONFIG['opinions_limit']
      @base_url = OPINIONS_CONFIG['domain']
      @api_end_point = OPINIONS_CONFIG['opinions_end_point']

      @api_url = "#{@base_url}/#{@api_end_point}"

      @total_pages =  23
      @query_parameters = request.query_parameters.slice(:page, :size)

      if @total_pages > 0
        @current_page = params[:page].to_i > 0 ? params[:page].to_i : 1
        @last_page = @current_page + 5 <= 10 ? 10 : @current_page + 5
        if @last_page > @total_pages
          @last_page = @total_pages
        end
        @first_page = @current_page - 5 > 0 && @current_page - 5 < @last_page  ? @current_page - 5 : 1
        @prev_page = @first_page -1 > 0 ? @first_page -1 : false
        @next_page = @last_page + 1 <= @total_pages ? @last_page + 1 : false
      else
        @total_pages = 0
      end

      @api_url = "#{@api_url}?offset=#{@current_page}&token=#{@ecommerce_id}&limit=#{@default_limit}"


      if params[:api]
        begin
          @fake_opinions = @opinions
          conn = Faraday.new @api_url
          response = conn.get
          response.status
          if status == 200
            @opinions = JSON.parse response.body
          else
            @opinions = @fake_opinions
            flash[:error] = "Ha ocurrido un error al conectar con el servidor"
          end
        rescue
          @opinions = @fake_opinions
          flash[:error] = "Ha ocurrido un error al conectar con el servidor"
        end
      end

    else
      flash[:error] = "Aqui no hay opiniones"
    end
  end

  def fake_api
    render json: @opinions
  end

  private

  def load_data
    @opinions = [{
          'id' => 2,
          'description' => "Despista un poco el rastreo del paquete. No es muy detallado. Por lo demás, el ordenador y características de mi Medion Akoya excelente, salvo en la batería que no dura apenas en comparación, quizás, a otras marcas.",
          'rating' => 5,
          'lang' => "es",
          'createdAt' => '2013-03-13 12:12',
          'username' => "Richard"
        },
        {
          'id' => 1,
          'description' => "La comparativa es muy clara y accesible y permite decidir con una amplia información. Resulta muy útil.",
          'rating' => 0,
          'lang' => "es",
          'createdAt' => '2013-03-14 12:12',
          'username' => "Smith"
        },
        {
          'id' => 4,
          'description' => "Los productos están bien presentados y bien especificados.",
          'rating' => 5,
          'lang' => "es",
          'createdAt' => '2013-03-15 12:12',
          'username' => "Paco"
        },
        {
          'id' => 4,
          'description' => "Estoy totalmente de acuerdo con todo, es una pena que la tienda online Medion en España haya cerrado, parecia muy interesante y solo pude efectuar dos compras.",
          'rating' => 2,
          'lang' => "es",
          'createdAt' => '2013-03-13 12:12',
          'username' => "Williams"
        }]
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Llistat d'opinions</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/opinions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <!-- page description -->
      <h1 class="text-center">Opinions of <%= request.host %></h1>
      <!-- end page description -->

      <!-- alert danger -->
      <%= render "shared/flash_message" %>

      <% if @ecommerce_id %>
        <ul class="stats text-center">
          <% (0..5).each do |rating| %>
            <%= link_to "".html_safe, client_opinions_path(@query_parameters.merge({:rating => rating})), {:class => "icon-face-#{rating} big-icon"} %>
          <% end %>
        </ul>
        <!-- end stats -->

        <!-- list -->
          <div class="media-list">
            <% @opinions.each do |opinion| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <%= link_to "".html_safe, client_opinions_path(@query_parameters.merge({:rating => opinion['rating']})), {:class => "pull-right icon-face-#{ opinion['rating']} small-icon"} %>
                  <h4><%= opinion['username']%> <small><%= opinion['createdAt'].to_time.to_formatted_s(:short) %></small></h4>
                </div>
                <div class="panel-body">
                  <%= opinion['description'] %>
                </div>
              </div>
            <% end %>
          </div>
        <!-- end list -->

        <% if @opinions && params[:ecommerce_id] && @total_pages > 1 %>
        <div class="text-center">
          <ul class="pagination">
            <% if @prev_page %>
              <li>
                <%= link_to "&laquo;".html_safe, client_opinions_path(@query_parameters.merge({:page => @prev_page})) %>
              </li>
            <% end %>
            <% (@first_page..@last_page).to_a.each do |page| %>
              <li class="<%= is_active = @current_page == page ? 'active' : '' %>">
                <%= link_to page, client_opinions_path(@query_parameters.merge({:page => page})) %>
              </li>
            <% end %>
            <% if @next_page %>
              <li>
                <%= link_to "&raquo;".html_safe, client_opinions_path(@query_parameters.merge({:page => @prev_page})) %>
              </li>
            <% end %>
          </ul>
          <% end %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
<% end %>